[package]
name = "nats"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitives = { path = "../primitives" }

serde_json = "1.0.68"
ratsio = "0.4.0"
tokio = "1.11.0"
