[package]
name = "nats"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratsio = "0.4.0"
primitives = { path = "../primitives" }
tokio = "1.11.0"
