// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct BalancesBalancesDecreaseSoftCurrencyParams {
    #[serde(rename = "txId")]
    pub tx_id: String,
    #[serde(rename = "amount")]
    pub amount: i32,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct BalancesBalancesDecreaseSoftCurrencyReturns {
    #[serde(rename = "balance")]
    pub balance: i32,
}
