// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
pub type BalancesBalancesFreeExperienceAddedNotificationParams = ();
#[derive(Debug, Serialize, Deserialize)]
pub struct BalancesBalancesFreeExperienceAddedNotificationReturns {
    #[serde(rename = "balance")]
    pub balance: i32,
    #[serde(rename = "amount")]
    pub amount: i32,
}
