// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
impl<'de> Deserialize<'de> for BalancesBalancesFreeExperienceAddedNotificationParams {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(BalancesBalancesFreeExperienceAddedNotificationParams)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct BalancesBalancesFreeExperienceAddedNotificationParams;
impl Schema for BalancesBalancesFreeExperienceAddedNotificationParams {
    fn schema() -> Value {
        todo!()
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BalancesBalancesFreeExperienceAddedNotificationReturns {
    #[serde(rename = "balance")]
    pub balance: i32,
    #[serde(rename = "amount")]
    pub amount: i32,
}
