[workspace]

members = [
    "db",
    "logger",
    "healthchecker",
    "request",
    "nats",
    "primitives",
    "utils"
]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
panic = "unwind"
