[workspace]

members = [
    "config",
    "db",
    "hashing",
    "healthchecker",
    "logger",
    "nats",
    "primitives",
    "request",
    "utils",
    "rust-lib"
]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
panic = "unwind"
