[workspace]
members = [
    "byte-formatter",
    "config",
    "error_registry",
    "macros",
    "topics",
    "topics/parser",
    "transport",
    "types",
    "vault",
    "async_logger",
    "blockchain",
    "json",
    "inner_db",
    "healthchecker",
]
