[package]
name = "rust-lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tokio-postgres = { version = "0.7.2", features = ["with-serde_json-1"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
serde = { version = "1.0.129", features = ["derive"] }
reqwest = { version = "0.11.4", features = ["json"] }
tokio = { version = "1.11.0", features = ["full"]}
tiny-bip39 = { version = "0.8", optional = true }
slog = { version = "2.7" }
slog-stdlog = "4.1.0"
hashicorp_vault = "2.1.0"
slog-envlogger = "2.2"
serde_json = "1.0.66"
hex-literal = "0.3.3"
tokio-service = "0.1"
block-modes = "0.8.1"
env_logger = "0.9.0"
thiserror = "1.0.26"
tokio-proto = "0.1"
slog-term = "2.8.0"
slog-scope = "4.3"
futures = "0.1.11"
slog-async = "2.5"
colored = "2.0.0"
chrono = "0.4.19"
slog-json = "2.3"
dotenv = "0.15.0"
ratsio = "0.4.0"
log = "0.4.14"
aes = "0.7.5"

[dev-dependencies]
rustc-serialize = "0.3"
num_cpus = "1.0"

# Custom dependencies
[dependencies.realis-primitives]
git = "https://github.com/RealisNetwork/Realis.Network.git"
branch = "main"
package = "realis-primitives"

[dependencies.runtime]
git =  "https://github.com/RealisNetwork/Realis.Network.git"
branch = "main"
package = "node-runtime"

[dependencies.sp-keyring]
git = "https://github.com/paritytech/substrate"
rev = "e7b93e1b1abcf0865824c68d10850bbb451e295f"

[dependencies.sp-core]
git = "https://github.com/paritytech/substrate"
rev = "e7b93e1b1abcf0865824c68d10850bbb451e295f"

[dependencies.substrate-api-client]
git = "https://github.com/RealisNetwork/substrate-api-client.git"

[dependencies.tokio-minihttp]
git = "https://github.com/tokio-rs/tokio-minihttp.git"


[features]
default = ["std"]
std = [
    #    "runtime/std",
    "tokio/full",
    "tiny-bip39",
]

full = [
    "async_logg",
    "config",
    "healthchecker",
    "ser_des-types",
    "logger",
    "nats",
    "vault"
]

async_logg = []

config = []
healthchecker = []
ser_des-types = []
logger = []
nats = []
vault = []
