// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthAuthProviderGetProviderByUserIdAndAppIdParams {
    #[serde(rename = "userId", deserialize_with = "deserialize_to_string")]
    pub user_id: String,
    #[serde(rename = "appId")]
    pub app_id: f64,
}
impl Schema for AuthAuthProviderGetProviderByUserIdAndAppIdParams {
    fn schema() -> Value {
        serde_json :: from_str ("{\"type\":\"object\",\"properties\":{\"userId\":{\"type\":\"string\"},\"appId\":{\"type\":\"integer\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807,\"additionalAttributes\":{\"numberType\":\"Number\"}}},\"required\":[\"userId\",\"appId\"]}") . unwrap ()
    }
}
impl Agent for AuthAuthProviderGetProviderByUserIdAndAppIdParams {
    fn topic() -> &'static str {
        "auth_authProvider_getProviderByUserIdAndAppId"
    }
    fn method() -> &'static str {
        "authProvider_getProviderByUserIdAndAppId"
    }
    fn agent() -> &'static str {
        "auth"
    }
    fn access_level() -> AccessLevel {
        AccessLevel::Internal
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthAuthProviderGetProviderByUserIdAndAppIdReturns(pub String);
impl Schema for AuthAuthProviderGetProviderByUserIdAndAppIdReturns {
    fn schema() -> Value {
        serde_json::json!("{\"type\":\"string\"}")
    }
}
impl Agent for AuthAuthProviderGetProviderByUserIdAndAppIdReturns {
    fn topic() -> &'static str {
        "auth_authProvider_getProviderByUserIdAndAppId"
    }
    fn method() -> &'static str {
        "authProvider_getProviderByUserIdAndAppId"
    }
    fn agent() -> &'static str {
        "auth"
    }
    fn access_level() -> AccessLevel {
        AccessLevel::Internal
    }
}
