// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct AuthAuthDeviceGetClientInfoParams {
    #[serde(rename = "provider")]
    pub provider: (),
    #[serde(rename = "providerId")]
    pub provider_id: String,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct AuthAuthDeviceGetClientInfoReturns {
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "isAuth")]
    pub is_auth: bool,
    #[serde(rename = "userId")]
    pub user_id: String,
}
