// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthAuthChangeMyEmailParams {
    #[serde(rename = "hash")]
    pub hash: String,
}
impl Schema for AuthAuthChangeMyEmailParams {
    fn schema() -> Value {
        todo!()
    }
}
pub type AuthAuthChangeMyEmailReturns = bool;
