// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct AuthAuthGetAccessTokenByRefreshParams {
    #[serde(rename = "refreshToken")]
    pub refresh_token: String,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct AuthAuthGetAccessTokenByRefreshReturns {
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(rename = "expires_in")]
    pub expires_in: i64,
}
