// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthBanBanParams {
    #[serde(rename = "userId")]
    pub user_id: String,
}
impl Schema for AuthBanBanParams {
    fn schema() -> Value {
        todo!()
    }
}
pub type AuthBanBanReturns = bool;
