// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthTwoFactorVerifyTokenParams {
    #[serde(rename = "token")]
    pub token: String,
}
impl Schema for AuthTwoFactorVerifyTokenParams {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"token\":{\"type\":\"string\"}},\"required\":[\"token\"]}")
    }
}
impl Agent for AuthTwoFactorVerifyTokenParams {
    fn topic() -> &'static str {
        "auth_twoFactor_verifyToken"
    }
    fn method() -> &'static str {
        "twoFactor_verifyToken"
    }
    fn agent() -> &'static str {
        "auth"
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthTwoFactorVerifyTokenReturns(bool);
impl Schema for AuthTwoFactorVerifyTokenReturns {
    fn schema() -> Value {
        serde_json::json!("{\"type\":\"boolean\"}")
    }
}
impl Agent for AuthTwoFactorVerifyTokenReturns {
    fn topic() -> &'static str {
        "auth_twoFactor_verifyToken"
    }
    fn method() -> &'static str {
        "twoFactor_verifyToken"
    }
    fn agent() -> &'static str {
        "auth"
    }
}
