[package]
name = "byte-formatter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realis-macros = { path = "../macros" }

bytebuffer-rs = "0.3.1"
