// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NearAdapterContractCallBurnNftParams {
    #[serde(rename = "nftId")]
    pub nft_id: String,
}
impl Schema for NearAdapterContractCallBurnNftParams {
    fn schema() -> Value {
        todo!()
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NearAdapterContractCallBurnNftReturns {
    #[serde(rename = "balance")]
    pub balance: String,
}
