// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NearAdapterContractCallTransferParams {
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "recipientUserId")]
    pub recipient_user_id: String,
}
impl Schema for NearAdapterContractCallTransferParams {
    fn schema() -> Value {
        todo!()
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NearAdapterContractCallTransferReturns {
    #[serde(rename = "balance")]
    pub balance: String,
}
