// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct NearAdapterContractCallMintNftParams {
    #[serde(rename = "recipientUserId")]
    pub recipient_user_id: String,
    #[serde(rename = "nftMetadata")]
    pub nft_metadata: String,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct NearAdapterContractCallMintNftReturns {
    #[serde(rename = "nftId")]
    pub nft_id: String,
}
