[package]
name = "healthchecker"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitives = { path = "../primitives" }
tokio-minihttp = { git = "https://github.com/tokio-rs/tokio-minihttp.git" }
tokio = { version = "1.11.0", features = ["full"] }
bytes = "0.4"
futures = "0.1.11"
httparse = "1.1.2"
log = "0.4"
tokio-core = "0.1.0"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"

[dev-dependencies]
rustc-serialize = "0.3"
num_cpus = "1.0"
env_logger = { version = "0.3.4", default-features = false }
serde_json = "0.8"
