// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct TransactionsBalanceGetBalancesByUserIdAsArrayReturnsParams {
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "currency")]
    pub currency: String,
}
pub type TransactionsBalanceGetBalancesByUserIdAsArrayReturns =
    Vec<TransactionsBalanceGetBalancesByUserIdAsArrayReturnsParams>;
