// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionsBalanceAdminIncreaseBalanceParamsExtraDetailParams(pub Value);
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionsBalanceAdminIncreaseBalanceParams {
    #[serde(rename = "currency", deserialize_with = "deserialize_to_string")]
    pub currency: String,
    #[serde(rename = "reason", deserialize_with = "deserialize_to_string")]
    pub reason: String,
    #[serde(rename = "creator", deserialize_with = "deserialize_to_string")]
    pub creator: String,
    #[serde(rename = "amount", deserialize_with = "deserialize_to_string")]
    pub amount: String,
    #[serde(rename = "txId", deserialize_with = "deserialize_to_string")]
    pub tx_id: String,
    #[serde(rename = "userId", deserialize_with = "deserialize_to_string")]
    pub user_id: String,
    #[serde(rename = "extraDetail")]
    pub extra_detail: Option<TransactionsBalanceAdminIncreaseBalanceParamsExtraDetailParams>,
}
impl Schema for TransactionsBalanceAdminIncreaseBalanceParams {
    fn schema() -> Value {
        serde_json :: from_str ("{\"type\":\"object\",\"properties\":{\"currency\":{\"type\":\"string\",\"pattern\":\"^(ETH)|(LIS)|(WLIS)|(TLIS)$\"},\"reason\":{\"type\":\"string\"},\"creator\":{\"type\":\"string\"},\"amount\":{\"type\":\"string\"},\"txId\":{\"type\":\"string\"},\"userId\":{\"type\":\"string\"},\"extraDetail\":{\"type\":\"object\",\"properties\":{}}},\"required\":[\"creator\",\"reason\",\"currency\",\"amount\",\"txId\",\"userId\"]}") . unwrap ()
    }
}
impl Agent for TransactionsBalanceAdminIncreaseBalanceParams {
    fn topic() -> &'static str {
        "transactions_balance_adminIncreaseBalance"
    }
    fn method() -> &'static str {
        "balance_adminIncreaseBalance"
    }
    fn agent() -> &'static str {
        "transactions"
    }
    fn access_level() -> AccessLevel {
        AccessLevel::Private
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionsBalanceAdminIncreaseBalanceReturns(pub Value);
impl Schema for TransactionsBalanceAdminIncreaseBalanceReturns {
    fn schema() -> Value {
        serde_json::json!("{\"type\":\"object\",\"properties\":{}}")
    }
}
impl Agent for TransactionsBalanceAdminIncreaseBalanceReturns {
    fn topic() -> &'static str {
        "transactions_balance_adminIncreaseBalance"
    }
    fn method() -> &'static str {
        "balance_adminIncreaseBalance"
    }
    fn agent() -> &'static str {
        "transactions"
    }
    fn access_level() -> AccessLevel {
        AccessLevel::Private
    }
}
