// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct TransactionsBalanceGetBalanceByUserIdParams {
    #[serde(rename = "currency")]
    pub currency: String,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct TransactionsBalanceGetBalanceByUserIdReturns {
    #[serde(rename = "amount")]
    pub amount: String,
}
