// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct BattlePassBattlePassEndpointsReceiveRewardParams {
    #[serde(rename = "bindingId")]
    pub binding_id: i32,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct BattlePassBattlePassEndpointsReceiveRewardReturns {
    #[serde(rename = "bindingId")]
    pub binding_id: i32,
}
