// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdminOptionSetParamsExtraDetailsParams {
    #[serde(rename = "tab")]
    pub tab: String,
    #[serde(rename = "type")]
    pub r#type: String,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdminOptionSetParams {
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "extraDetails")]
    pub extra_details: Option<AdminOptionSetParamsExtraDetailsParams>,
    #[serde(rename = "description")]
    pub description: Option<String>,
    #[serde(rename = "clientKey")]
    pub client_key: String,
}
impl Schema for AdminOptionSetParams {
    fn schema() -> Value {
        todo!()
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdminOptionSetReturns {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
}
