// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct AdminOptionSetParamsExtraDetailsParams {
    #[serde(rename = "type")]
    r#type: String,
    #[serde(rename = "tab")]
    pub tab: String,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct AdminOptionSetParams {
    #[serde(rename = "extraDetails")]
    pub extra_details: AdminOptionSetParamsExtraDetailsParams,
    #[serde(rename = "clientKey")]
    pub client_key: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "description")]
    pub description: String,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct AdminOptionSetReturns {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
}
