// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdminOptionGetParams {
    #[serde(rename = "clientKey")]
    pub client_key: String,
}
impl Schema for AdminOptionGetParams {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"clientKey\":{\"type\":\"string\"}},\"required\":[\"clientKey\"]}")
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdminOptionGetReturns {
    #[serde(rename = "scope")]
    pub scope: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "key")]
    pub key: String,
}
impl Schema for AdminOptionGetReturns {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"scope\":{\"type\":\"string\"},\"value\":{\"type\":\"string\"},\"key\":{\"type\":\"string\"}},\"required\":[\"scope\",\"key\",\"value\"]}")
    }
}
