// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
pub type AdminUserRoleGetAllParams = ();
#[derive(Debug, Serialize, Deserialize)]
pub struct AdminUserRoleGetAllReturnsParamsRoleParams {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "name")]
    pub name: String,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct AdminUserRoleGetAllReturnsParams {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "isActive")]
    pub is_active: bool,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "role")]
    pub role: AdminUserRoleGetAllReturnsParamsRoleParams,
}
pub type AdminUserRoleGetAllReturns = Vec<AdminUserRoleGetAllReturnsParams>;
