// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct DragocatsStorageInventoryEndpointsEquipUnitParams {
    #[serde(rename = "unitId")]
    pub unit_id: i32,
    #[serde(rename = "slotId")]
    pub slot_id: i32,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct DragocatsStorageInventoryEndpointsEquipUnitReturns {
    #[serde(rename = "slotId")]
    pub slot_id: i32,
    #[serde(rename = "unitId")]
    pub unit_id: i32,
}
