// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
pub type DragocatsStorageInventoryEndpointsOpenLootboxNotificationParams = ();
#[derive(Debug, Serialize, Deserialize)]
pub struct DragocatsStorageInventoryEndpointsOpenLootboxNotificationReturns {}
