[package]
name = "transport"
version = "0.1.0"
edition = "2021"

[dependencies]
error_registry = { path = "../error_registry" }

async-trait = "0.1.56"
enum_dispatch = "0.3.8"
serde_json = "1.0.81"
serde = "1.0.137"
tokio = "1.19.2"
stan = "0.0.16"
nats = "0.9.18"
