[package]
name = "transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
tokio = { version = "1.15.0", features = ["sync", "time"] }

ratsio = { git = "https://github.com/RealisNetwork/ratsio.git", optional= true }

[features]
nats = [
    "ratsio",
]