[package]
name = "transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
futures = "0.3.19"
tokio = { version = "1.15.0", features = ["sync", "time"] }
rust-lib = { path = "../../rust-lib", optional = true }

ratsio = { git = "https://github.com/RealisNetwork/ratsio.git", optional= true }

[features]
nats = [
    "rust-lib/error_registry",
    "ratsio",
]
