[package]
name = "error_registry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realis-macros = {path = "../macros"}

deadpool-postgres = "0.10.1"
convert_case = "0.5.0"
derive_more = "0.99.17"
serde_json = "1.0.78"
thiserror = "1.0.30"
strum_macros = "0.23.1"
backoff = "0.4.0"
strum = "0.23.0"
log = "0.4.14"

serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.16.1", features = ["time"]}