// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CatsLobbyGetUserIdByTransactionIdParams {
    #[serde(rename = "transactionId")]
    pub transaction_id: String,
}
impl Schema for CatsLobbyGetUserIdByTransactionIdParams {
    fn schema() -> Value {
        serde_json :: from_str ("{\"type\":\"object\",\"properties\":{\"transactionId\":{\"type\":\"string\"}},\"required\":[\"transactionId\"]}") . unwrap ()
    }
}
impl Agent for CatsLobbyGetUserIdByTransactionIdParams {
    fn topic() -> &'static str {
        "cats_lobby_getUserIdByTransactionId"
    }
    fn method() -> &'static str {
        "lobby_getUserIdByTransactionId"
    }
    fn agent() -> &'static str {
        "cats"
    }
    fn access_level() -> AccessLevel {
        AccessLevel::Public
    }
}
impl<'de> Deserialize<'de> for CatsLobbyGetUserIdByTransactionIdReturns {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        serde_json::Value::deserialize(deserializer)?;
        Ok(CatsLobbyGetUserIdByTransactionIdReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct CatsLobbyGetUserIdByTransactionIdReturns;
impl Schema for CatsLobbyGetUserIdByTransactionIdReturns {
    fn schema() -> Value {
        serde_json::json!("{}")
    }
}
impl Agent for CatsLobbyGetUserIdByTransactionIdReturns {
    fn topic() -> &'static str {
        "cats_lobby_getUserIdByTransactionId"
    }
    fn method() -> &'static str {
        "lobby_getUserIdByTransactionId"
    }
    fn agent() -> &'static str {
        "cats"
    }
    fn access_level() -> AccessLevel {
        AccessLevel::Public
    }
}
