// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CatsLobbyGetJackpotWinnersInfoParams {
    #[serde(rename = "userId")]
    pub user_id: String,
}
impl Schema for CatsLobbyGetJackpotWinnersInfoParams {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"userId\":{\"type\":\"string\"}},\"required\":[\"userId\"]}")
    }
}
impl Agent for CatsLobbyGetJackpotWinnersInfoParams {
    fn topic() -> &'static str {
        "cats_lobby_getJackpotWinnersInfo"
    }
    fn method() -> &'static str {
        "lobby_getJackpotWinnersInfo"
    }
    fn agent() -> &'static str {
        "cats"
    }
}
impl<'de> Deserialize<'de> for CatsLobbyGetJackpotWinnersInfoReturns {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        serde_json::Value::deserialize(deserializer)?;
        Ok(CatsLobbyGetJackpotWinnersInfoReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct CatsLobbyGetJackpotWinnersInfoReturns;
impl Schema for CatsLobbyGetJackpotWinnersInfoReturns {
    fn schema() -> Value {
        serde_json::json!("{}")
    }
}
impl Agent for CatsLobbyGetJackpotWinnersInfoReturns {
    fn topic() -> &'static str {
        "cats_lobby_getJackpotWinnersInfo"
    }
    fn method() -> &'static str {
        "lobby_getJackpotWinnersInfo"
    }
    fn agent() -> &'static str {
        "cats"
    }
}
