// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CatsLobbyBuyCatParams {
    #[serde(rename = "price")]
    pub price: i64,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "catId")]
    pub cat_id: i64,
}
impl Schema for CatsLobbyBuyCatParams {
    fn schema() -> Value {
        todo!()
    }
}
impl<'de> Deserialize<'de> for CatsLobbyBuyCatReturns {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(CatsLobbyBuyCatReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct CatsLobbyBuyCatReturns;
