// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CatsLobbyGetUsersReferralsParams {
    #[serde(rename = "userId")]
    pub user_id: String,
}
impl Schema for CatsLobbyGetUsersReferralsParams {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"userId\":{\"type\":\"string\"}},\"required\":[\"userId\"]}")
    }
}
impl Agent for CatsLobbyGetUsersReferralsParams {
    fn topic() -> &'static str {
        "cats_lobby_getUsersReferrals"
    }
    fn method() -> &'static str {
        "lobby_getUsersReferrals"
    }
    fn agent() -> &'static str {
        "cats"
    }
}
impl<'de> Deserialize<'de> for CatsLobbyGetUsersReferralsReturns {
    fn deserialize<D>(_deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(CatsLobbyGetUsersReferralsReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct CatsLobbyGetUsersReferralsReturns;
impl Schema for CatsLobbyGetUsersReferralsReturns {
    fn schema() -> Value {
        serde_json::json!("{}")
    }
}
impl Agent for CatsLobbyGetUsersReferralsReturns {
    fn topic() -> &'static str {
        "cats_lobby_getUsersReferrals"
    }
    fn method() -> &'static str {
        "lobby_getUsersReferrals"
    }
    fn agent() -> &'static str {
        "cats"
    }
}
