// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameBalancerBalancerEndpointsAddBotsParams {
    #[serde(rename = "region")]
    pub region: String,
}
impl Schema for GameBalancerBalancerEndpointsAddBotsParams {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"region\":{\"type\":\"string\"}},\"required\":[\"region\"]}")
    }
}
impl Agent for GameBalancerBalancerEndpointsAddBotsParams {
    fn topic() -> &'static str {
        "gameBalancer_balancerEndpoints_addBots"
    }
    fn method() -> &'static str {
        "balancerEndpoints_addBots"
    }
    fn agent() -> &'static str {
        "gameBalancer"
    }
}
impl<'de> Deserialize<'de> for GameBalancerBalancerEndpointsAddBotsReturns {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        serde_json::Value::deserialize(deserializer)?;
        Ok(GameBalancerBalancerEndpointsAddBotsReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct GameBalancerBalancerEndpointsAddBotsReturns;
impl Schema for GameBalancerBalancerEndpointsAddBotsReturns {
    fn schema() -> Value {
        serde_json::json!("{}")
    }
}
impl Agent for GameBalancerBalancerEndpointsAddBotsReturns {
    fn topic() -> &'static str {
        "gameBalancer_balancerEndpoints_addBots"
    }
    fn method() -> &'static str {
        "balancerEndpoints_addBots"
    }
    fn agent() -> &'static str {
        "gameBalancer"
    }
}
