// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct GameBalancerGameBalancerAddPlayerInSearchParamsStatsParams {
    #[serde(rename = "skillEffectPower")]
    pub skill_effect_power: i16,
    #[serde(rename = "strength")]
    pub strength: i16,
    #[serde(rename = "moveSpeed")]
    pub move_speed: i16,
    #[serde(rename = "skillPower")]
    pub skill_power: i16,
    #[serde(rename = "ultRange")]
    pub ult_range: i16,
    #[serde(rename = "attackSpeed")]
    pub attack_speed: i16,
    #[serde(rename = "dashSpeed")]
    pub dash_speed: i16,
    #[serde(rename = "ultChargeSpeed")]
    pub ult_charge_speed: i16,
    #[serde(rename = "skillRange")]
    pub skill_range: i16,
    #[serde(rename = "attackCritChance")]
    pub attack_crit_chance: i16,
    #[serde(rename = "ultArmor")]
    pub ult_armor: i16,
    #[serde(rename = "agility")]
    pub agility: i16,
    #[serde(rename = "ultEffectPower")]
    pub ult_effect_power: i16,
    #[serde(rename = "attackArmor")]
    pub attack_armor: i16,
    #[serde(rename = "attackDamage")]
    pub attack_damage: i16,
    #[serde(rename = "ultPower")]
    pub ult_power: i16,
    #[serde(rename = "attackCritMultiple")]
    pub attack_crit_multiple: i16,
    #[serde(rename = "damageReturnPower")]
    pub damage_return_power: i16,
    #[serde(rename = "dashRange")]
    pub dash_range: i16,
    #[serde(rename = "attackReloadSpeed")]
    pub attack_reload_speed: i16,
    #[serde(rename = "vampirismPower")]
    pub vampirism_power: i16,
    #[serde(rename = "mainStat")]
    pub main_stat: i8,
    #[serde(rename = "intelligence")]
    pub intelligence: i16,
    #[serde(rename = "skillArmor")]
    pub skill_armor: i16,
    #[serde(rename = "skillReloadSpeed")]
    pub skill_reload_speed: i16,
    #[serde(rename = "dashReloadSpeed")]
    pub dash_reload_speed: i16,
    #[serde(rename = "healthRegenPercent")]
    pub health_regen_percent: i16,
    #[serde(rename = "damage")]
    pub damage: i16,
    #[serde(rename = "attackRange")]
    pub attack_range: i16,
    #[serde(rename = "health")]
    pub health: i16,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct GameBalancerGameBalancerAddPlayerInSearchParams {
    #[serde(rename = "nickname")]
    pub nickname: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "region")]
    pub region: String,
    #[serde(rename = "heroType")]
    pub hero_type: String,
    #[serde(rename = "stats")]
    pub stats: GameBalancerGameBalancerAddPlayerInSearchParamsStatsParams,
}
pub type GameBalancerGameBalancerAddPlayerInSearchReturns = bool;
