// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
impl<'de> Deserialize<'de> for MarketPlaceMarketPlaceGetCanceledItemsParams {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(MarketPlaceMarketPlaceGetCanceledItemsParams)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct MarketPlaceMarketPlaceGetCanceledItemsParams;
impl Schema for MarketPlaceMarketPlaceGetCanceledItemsParams {
    fn schema() -> Value {
        todo!()
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketPlaceMarketPlaceGetCanceledItemsReturnsParams {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "productId")]
    pub product_id: i32,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "createdAt")]
    pub created_at: i32,
}
pub type MarketPlaceMarketPlaceGetCanceledItemsReturns =
    Vec<MarketPlaceMarketPlaceGetCanceledItemsReturnsParams>;
