// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketPlaceMarketPlaceGetItemsByFilterParamsOrderParams {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "desc")]
    pub desc: bool,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketPlaceMarketPlaceGetItemsByFilterParamsPriceParams {
    #[serde(rename = "min")]
    pub min: i32,
    #[serde(rename = "max")]
    pub max: i32,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketPlaceMarketPlaceGetItemsByFilterParams {
    #[serde(rename = "perPage")]
    pub per_page: i32,
    #[serde(rename = "personalType")]
    pub personal_type: Option<String>,
    #[serde(rename = "order")]
    pub order: Option<MarketPlaceMarketPlaceGetItemsByFilterParamsOrderParams>,
    #[serde(rename = "price")]
    pub price: Option<MarketPlaceMarketPlaceGetItemsByFilterParamsPriceParams>,
    #[serde(rename = "additionalParam")]
    pub additional_param: Option<String>,
    #[serde(rename = "category")]
    pub category: Option<i32>,
    #[serde(rename = "page")]
    pub page: i32,
    #[serde(rename = "additionalValue")]
    pub additional_value: Option<String>,
}
impl Schema for MarketPlaceMarketPlaceGetItemsByFilterParams {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"perPage\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}},\"personalType\":{\"type\":\"string\"},\"order\":{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\"},\"desc\":{\"type\":\"boolean\"}},\"required\":[\"name\",\"desc\"]},\"price\":{\"type\":\"object\",\"properties\":{\"min\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}},\"max\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}}},\"required\":[\"min\",\"max\"]},\"additionalParam\":{\"type\":\"string\"},\"category\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}},\"page\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}},\"additionalValue\":{\"type\":\"string\"}},\"required\":[\"perPage\",\"page\"]}")
    }
}
impl Agent for MarketPlaceMarketPlaceGetItemsByFilterParams {
    fn topic() -> &'static str {
        "market-place_marketPlace_getItemsByFilter"
    }
    fn method() -> &'static str {
        "marketPlace_getItemsByFilter"
    }
    fn agent() -> &'static str {
        "market-place"
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketPlaceMarketPlaceGetItemsByFilterReturnsParamsAdditionalParamsParams {}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketPlaceMarketPlaceGetItemsByFilterReturnsParams {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "subType")]
    pub sub_type: String,
    #[serde(rename = "productId")]
    pub product_id: i32,
    #[serde(rename = "personalType")]
    pub personal_type: String,
    #[serde(rename = "price")]
    pub price: i32,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "isLocked")]
    pub is_locked: bool,
    #[serde(rename = "category")]
    pub category: i32,
    #[serde(rename = "createdAt")]
    pub created_at: i32,
    #[serde(rename = "updatedAt")]
    pub updated_at: i32,
    #[serde(rename = "additionalParams")]
    pub additional_params:
        MarketPlaceMarketPlaceGetItemsByFilterReturnsParamsAdditionalParamsParams,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketPlaceMarketPlaceGetItemsByFilterReturns(
    Vec<MarketPlaceMarketPlaceGetItemsByFilterReturnsParams>,
);
impl Schema for MarketPlaceMarketPlaceGetItemsByFilterReturns {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"userId\":{\"type\":\"string\"},\"id\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}},\"subType\":{\"type\":\"string\"},\"productId\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}},\"personalType\":{\"type\":\"string\"},\"price\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}},\"type\":{\"type\":\"string\"},\"isLocked\":{\"type\":\"boolean\"},\"category\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}},\"createdAt\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}},\"updatedAt\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}},\"additionalParams\":{\"type\":\"object\",\"properties\":{},\"required\":null}},\"required\":[\"id\",\"productId\",\"userId\",\"personalType\",\"type\",\"subType\",\"price\",\"additionalParams\",\"isLocked\",\"category\",\"createdAt\",\"updatedAt\"]}}")
    }
}
impl Agent for MarketPlaceMarketPlaceGetItemsByFilterReturns {
    fn topic() -> &'static str {
        "market-place_marketPlace_getItemsByFilter"
    }
    fn method() -> &'static str {
        "marketPlace_getItemsByFilter"
    }
    fn agent() -> &'static str {
        "market-place"
    }
}
