// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CronCronGetParams {
    #[serde(rename = "id")]
    pub id: i64,
}
impl Schema for CronCronGetParams {
    fn schema() -> Value {
        todo!()
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CronCronGetReturns {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "startsAt")]
    pub starts_at: String,
    #[serde(rename = "howOften")]
    pub how_often: i64,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}
