// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
impl<'de> Deserialize<'de> for StatusConfigGetListParams {
    fn deserialize<D>(_deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(StatusConfigGetListParams)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct StatusConfigGetListParams;
impl Schema for StatusConfigGetListParams {
    fn schema() -> Value {
        serde_json::json!("{}")
    }
}
impl Agent for StatusConfigGetListParams {
    fn topic() -> &'static str {
        "status_config_getList"
    }
    fn method() -> &'static str {
        "config_getList"
    }
    fn agent() -> &'static str {
        "status"
    }
}
impl<'de> Deserialize<'de> for StatusConfigGetListReturns {
    fn deserialize<D>(_deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(StatusConfigGetListReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct StatusConfigGetListReturns;
impl Schema for StatusConfigGetListReturns {
    fn schema() -> Value {
        serde_json::json!("{}")
    }
}
impl Agent for StatusConfigGetListReturns {
    fn topic() -> &'static str {
        "status_config_getList"
    }
    fn method() -> &'static str {
        "config_getList"
    }
    fn agent() -> &'static str {
        "status"
    }
}
