// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct StatusConfigAddParams {
    #[serde(rename = "maxCount")]
    pub max_count: String,
    #[serde(rename = "isAvailable")]
    pub is_available: bool,
    #[serde(rename = "membership")]
    pub membership: String,
    #[serde(rename = "multiplier")]
    pub multiplier: String,
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "priceInLis")]
    pub price_in_lis: String,
}
pub type StatusConfigAddReturns = bool;
