// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
pub type ReferralLinkGetAllMyParams = ();
#[derive(Debug, Serialize, Deserialize)]
pub struct ReferralLinkGetAllMyReturnsReferralLinksParamsParams {
    #[serde(rename = "appId")]
    pub app_id: i64,
    #[serde(rename = "link")]
    pub link: String,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct ReferralLinkGetAllMyReturns {
    #[serde(rename = "referralCode")]
    pub referral_code: String,
    #[serde(rename = "referralLinks")]
    pub referral_links: Vec<ReferralLinkGetAllMyReturnsReferralLinksParamsParams>,
}
