// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReferralReferralAddReferralParams {
    #[serde(rename = "referralId")]
    pub referral_id: String,
    #[serde(rename = "referrerId")]
    pub referrer_id: String,
}
impl Schema for ReferralReferralAddReferralParams {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"referralId\":{\"type\":\"string\"},\"referrerId\":{\"type\":\"string\"}},\"required\":[\"referralId\",\"referrerId\"]}")
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReferralReferralAddReferralReturns(bool);
impl Schema for ReferralReferralAddReferralReturns {
    fn schema() -> Value {
        serde_json::json!("{\"type\":\"boolean\"}")
    }
}
