// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReferralRewardGetAvailableRewardParams {
    #[serde(rename = "referrerId")]
    pub referrer_id: String,
}
impl Schema for ReferralRewardGetAvailableRewardParams {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"referrerId\":{\"type\":\"string\"}},\"required\":[\"referrerId\"]}")
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReferralRewardGetAvailableRewardReturns(String);
impl Schema for ReferralRewardGetAvailableRewardReturns {
    fn schema() -> Value {
        serde_json::json!("{\"type\":\"string\"}")
    }
}
