// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DragocatsBalancerBalancerLeaveQueueParams(Value);
impl Schema for DragocatsBalancerBalancerLeaveQueueParams {
    fn schema() -> Value {
        serde_json::from_str("{\"type\":\"object\",\"properties\":{}}").unwrap()
    }
}
impl Agent for DragocatsBalancerBalancerLeaveQueueParams {
    fn topic() -> &'static str {
        "dragocats-balancer_balancer_leaveQueue"
    }
    fn method() -> &'static str {
        "balancer_leaveQueue"
    }
    fn agent() -> &'static str {
        "dragocats-balancer"
    }
    fn access_level() -> AccessLevel {
        AccessLevel::Internal
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DragocatsBalancerBalancerLeaveQueueReturns(pub bool);
impl Schema for DragocatsBalancerBalancerLeaveQueueReturns {
    fn schema() -> Value {
        serde_json::json!("{\"type\":\"boolean\"}")
    }
}
impl Agent for DragocatsBalancerBalancerLeaveQueueReturns {
    fn topic() -> &'static str {
        "dragocats-balancer_balancer_leaveQueue"
    }
    fn method() -> &'static str {
        "balancer_leaveQueue"
    }
    fn agent() -> &'static str {
        "dragocats-balancer"
    }
    fn access_level() -> AccessLevel {
        AccessLevel::Internal
    }
}
