// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProductFactoryLootboxTypeUpdateByLootboxIdParams {
    #[serde(rename = "name")]
    pub name: Option<String>,
    #[serde(rename = "dropChanceMultiplier")]
    pub drop_chance_multiplier: Option<i32>,
    #[serde(rename = "lootboxId")]
    pub lootbox_id: i32,
    #[serde(rename = "type")]
    pub r#type: Option<String>,
}
impl Schema for ProductFactoryLootboxTypeUpdateByLootboxIdParams {
    fn schema() -> Value {
        todo!()
    }
}
pub type ProductFactoryLootboxTypeUpdateByLootboxIdReturns = bool;
