// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
impl<'de> Deserialize<'de> for EmailEmailFindAllParams {
    fn deserialize<D>(_deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(EmailEmailFindAllParams)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct EmailEmailFindAllParams;
impl Schema for EmailEmailFindAllParams {
    fn schema() -> Value {
        serde_json::json!("{}")
    }
}
impl<'de> Deserialize<'de> for EmailEmailFindAllReturns {
    fn deserialize<D>(_deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(EmailEmailFindAllReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct EmailEmailFindAllReturns;
impl Schema for EmailEmailFindAllReturns {
    fn schema() -> Value {
        serde_json::json!("{}")
    }
}
