// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DragonsLobbyCompleteTaskParams {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "taskId")]
    pub task_id: f64,
}
impl Schema for DragonsLobbyCompleteTaskParams {
    fn schema() -> Value {
        serde_json :: from_str ("{\"type\":\"object\",\"properties\":{\"userId\":{\"type\":\"string\"},\"taskId\":{\"type\":\"integer\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807,\"additionalAttributes\":{\"numberType\":\"Number\"}}},\"required\":[\"userId\",\"taskId\"]}") . unwrap ()
    }
}
impl Agent for DragonsLobbyCompleteTaskParams {
    fn topic() -> &'static str {
        "dragons_lobby_completeTask"
    }
    fn method() -> &'static str {
        "lobby_completeTask"
    }
    fn agent() -> &'static str {
        "dragons"
    }
}
impl<'de> Deserialize<'de> for DragonsLobbyCompleteTaskReturns {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        serde_json::Value::deserialize(deserializer)?;
        Ok(DragonsLobbyCompleteTaskReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct DragonsLobbyCompleteTaskReturns;
impl Schema for DragonsLobbyCompleteTaskReturns {
    fn schema() -> Value {
        serde_json::json!("{}")
    }
}
impl Agent for DragonsLobbyCompleteTaskReturns {
    fn topic() -> &'static str {
        "dragons_lobby_completeTask"
    }
    fn method() -> &'static str {
        "lobby_completeTask"
    }
    fn agent() -> &'static str {
        "dragons"
    }
}
