// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
impl<'de> Deserialize<'de> for DragonsLobbyGetSoulPriceParams {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(DragonsLobbyGetSoulPriceParams)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct DragonsLobbyGetSoulPriceParams;
impl Schema for DragonsLobbyGetSoulPriceParams {
    fn schema() -> Value {
        todo!()
    }
}
impl<'de> Deserialize<'de> for DragonsLobbyGetSoulPriceReturns {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(DragonsLobbyGetSoulPriceReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct DragonsLobbyGetSoulPriceReturns;
