// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DragonsLobbySaveTutorialProgressParams {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "dataObject")]
    pub data_object: String,
}
impl Schema for DragonsLobbySaveTutorialProgressParams {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"userId\":{\"type\":\"string\"},\"dataObject\":{\"type\":\"string\"}},\"required\":[\"userId\",\"dataObject\"]}")
    }
}
impl Agent for DragonsLobbySaveTutorialProgressParams {
    fn topic() -> &'static str {
        "dragons_lobby_saveTutorialProgress"
    }
    fn method() -> &'static str {
        "lobby_saveTutorialProgress"
    }
    fn agent() -> &'static str {
        "dragons"
    }
}
impl<'de> Deserialize<'de> for DragonsLobbySaveTutorialProgressReturns {
    fn deserialize<D>(_deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(DragonsLobbySaveTutorialProgressReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct DragonsLobbySaveTutorialProgressReturns;
impl Schema for DragonsLobbySaveTutorialProgressReturns {
    fn schema() -> Value {
        serde_json::json!("{}")
    }
}
impl Agent for DragonsLobbySaveTutorialProgressReturns {
    fn topic() -> &'static str {
        "dragons_lobby_saveTutorialProgress"
    }
    fn method() -> &'static str {
        "lobby_saveTutorialProgress"
    }
    fn agent() -> &'static str {
        "dragons"
    }
}
