// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
impl<'de> Deserialize<'de> for DragonsLobbyGetCurrentTasksParams {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(DragonsLobbyGetCurrentTasksParams)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct DragonsLobbyGetCurrentTasksParams;
impl Schema for DragonsLobbyGetCurrentTasksParams {
    fn schema() -> Value {
        todo!()
    }
}
impl<'de> Deserialize<'de> for DragonsLobbyGetCurrentTasksReturns {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(DragonsLobbyGetCurrentTasksReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct DragonsLobbyGetCurrentTasksReturns;
