[package]
name = "realis-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.34"
quote = "1.0"
syn = "1.0"
serde_json = "1.0.71"
convert_case = "0.4.0"
