// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct RefundItemsDeleteParams {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "hashItemId")]
    pub hash_item_id: i64,
}
pub type RefundItemsDeleteReturns = bool;
