// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LobbyHeroesEndpointsEquipHeroParams {
    #[serde(rename = "bindingId")]
    pub binding_id: i32,
}
impl Schema for LobbyHeroesEndpointsEquipHeroParams {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"bindingId\":{\"type\":\"integer\",\"minimum\":-2147483648,\"maximum\":2147483647,\"additionalAttributes\":{\"numberType\":\"Int\"}}},\"required\":[\"bindingId\"]}")
    }
}
impl<'de> Deserialize<'de> for LobbyHeroesEndpointsEquipHeroReturns {
    fn deserialize<D>(_deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Ok(LobbyHeroesEndpointsEquipHeroReturns)
    }
}
#[derive(Debug, Clone, Serialize)]
pub struct LobbyHeroesEndpointsEquipHeroReturns;
impl Schema for LobbyHeroesEndpointsEquipHeroReturns {
    fn schema() -> Value {
        serde_json::json!("{}")
    }
}
