// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct PurchaseProductGetHeroListReturnsParamsStatsParams {
    #[serde(rename = "mainCharacteristic")]
    pub main_characteristic: i8,
    #[serde(rename = "ultEffectPower")]
    pub ult_effect_power: i32,
    #[serde(rename = "intelligence")]
    pub intelligence: i32,
    #[serde(rename = "ultPower")]
    pub ult_power: i32,
    #[serde(rename = "health")]
    pub health: i32,
    #[serde(rename = "skillEffectPower")]
    pub skill_effect_power: i32,
    #[serde(rename = "attackReloadSpeed")]
    pub attack_reload_speed: String,
    #[serde(rename = "attackDamage")]
    pub attack_damage: i32,
    #[serde(rename = "agility")]
    pub agility: i32,
    #[serde(rename = "strength")]
    pub strength: i32,
    #[serde(rename = "skillPower")]
    pub skill_power: i32,
    #[serde(rename = "vampirismPower")]
    pub vampirism_power: String,
    #[serde(rename = "healthRegenPercent")]
    pub health_regen_percent: String,
    #[serde(rename = "armor")]
    pub armor: String,
    #[serde(rename = "moveSpeed")]
    pub move_speed: String,
}
#[derive(Debug, Serialize, Deserialize)]
pub struct PurchaseProductGetHeroListReturnsParams {
    #[serde(rename = "productType")]
    pub product_type: String,
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "stats")]
    pub stats: PurchaseProductGetHeroListReturnsParamsStatsParams,
    #[serde(rename = "heroId")]
    pub hero_id: i8,
}
pub type PurchaseProductGetHeroListReturns = Vec<PurchaseProductGetHeroListReturnsParams>;
