// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfileGetAllProfilesParams {
    #[serde(rename = "page")]
    pub page: f64,
    #[serde(rename = "perPage")]
    pub per_page: f64,
}
impl Schema for UserProfileGetAllProfilesParams {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"page\":{\"type\":\"integer\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807,\"additionalAttributes\":{\"numberType\":\"Number\"}},\"perPage\":{\"type\":\"integer\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807,\"additionalAttributes\":{\"numberType\":\"Number\"}}},\"required\":[\"page\",\"perPage\"]}")
    }
}
impl Agent for UserProfileGetAllProfilesParams {
    fn topic() -> &'static str {
        "user_profile_getAllProfiles"
    }
    fn method() -> &'static str {
        "profile_getAllProfiles"
    }
    fn agent() -> &'static str {
        "user"
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfileGetAllProfilesReturnsParamsBanParams {
    #[serde(rename = "id")]
    pub id: f64,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "whoBanned")]
    pub who_banned: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "bannedUntil")]
    pub banned_until: String,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfileGetAllProfilesReturnsParams {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "isNicknameChanged")]
    pub is_nickname_changed: bool,
    #[serde(rename = "isBanned")]
    pub is_banned: bool,
    #[serde(rename = "nickname")]
    pub nickname: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "isConfirmed")]
    pub is_confirmed: bool,
    #[serde(rename = "lifeTimeInterestPercent")]
    pub life_time_interest_percent: String,
    #[serde(rename = "id")]
    pub id: f64,
    #[serde(rename = "notice")]
    pub notice: String,
    #[serde(rename = "isDeleted")]
    pub is_deleted: bool,
    #[serde(rename = "hasPassword")]
    pub has_password: bool,
    #[serde(rename = "suspicious")]
    pub suspicious: bool,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "ban")]
    pub ban: UserProfileGetAllProfilesReturnsParamsBanParams,
    #[serde(rename = "isSubscribedToMailing")]
    pub is_subscribed_to_mailing: bool,
    #[serde(rename = "lifeTimeInterest")]
    pub life_time_interest: bool,
    #[serde(rename = "registeredAt")]
    pub registered_at: String,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfileGetAllProfilesReturns(pub Vec<UserProfileGetAllProfilesReturnsParams>);
impl Schema for UserProfileGetAllProfilesReturns {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"userId\":{\"type\":\"string\"},\"isNicknameChanged\":{\"type\":\"boolean\"},\"isBanned\":{\"type\":\"boolean\"},\"nickname\":{\"type\":\"string\"},\"email\":{\"type\":\"string\"},\"isConfirmed\":{\"type\":\"boolean\"},\"lifeTimeInterestPercent\":{\"type\":\"string\"},\"id\":{\"type\":\"integer\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807,\"additionalAttributes\":{\"numberType\":\"Number\"}},\"notice\":{\"type\":\"string\"},\"isDeleted\":{\"type\":\"boolean\"},\"hasPassword\":{\"type\":\"boolean\"},\"suspicious\":{\"type\":\"boolean\"},\"verified\":{\"type\":\"boolean\"},\"ban\":{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"integer\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807,\"additionalAttributes\":{\"numberType\":\"Number\"}},\"createdAt\":{\"type\":\"string\"},\"updatedAt\":{\"type\":\"string\"},\"whoBanned\":{\"type\":\"string\"},\"reason\":{\"type\":\"string\"},\"bannedUntil\":{\"type\":\"string\"}},\"required\":[\"id\",\"reason\",\"whoBanned\",\"createdAt\",\"updatedAt\",\"bannedUntil\"]},\"isSubscribedToMailing\":{\"type\":\"boolean\"},\"lifeTimeInterest\":{\"type\":\"boolean\"},\"registeredAt\":{\"type\":\"string\"}},\"required\":[\"id\",\"userId\",\"nickname\",\"email\",\"verified\",\"isNicknameChanged\",\"isSubscribedToMailing\",\"suspicious\",\"isConfirmed\",\"notice\",\"isBanned\",\"isDeleted\",\"hasPassword\",\"ban\",\"registeredAt\",\"lifeTimeInterest\",\"lifeTimeInterestPercent\"]}}")
    }
}
impl Agent for UserProfileGetAllProfilesReturns {
    fn topic() -> &'static str {
        "user_profile_getAllProfiles"
    }
    fn method() -> &'static str {
        "profile_getAllProfiles"
    }
    fn agent() -> &'static str {
        "user"
    }
}
