// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use serde::{Deserialize, Serialize};
#[derive(Debug, Serialize, Deserialize)]
pub struct UserProfileBanProfileParams {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "reason")]
    pub reason: String,
}
pub type UserProfileBanProfileReturns = bool;
