// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::generated_schemas::prelude::*;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfileGetProfileParams {
    #[serde(rename = "userId")]
    pub user_id: String,
}
impl Schema for UserProfileGetProfileParams {
    fn schema() -> Value {
        serde_json :: from_str ("{\"type\":\"object\",\"properties\":{\"userId\":{\"type\":\"string\"}},\"required\":[\"userId\"]}") . unwrap ()
    }
}
impl Agent for UserProfileGetProfileParams {
    fn topic() -> &'static str {
        "user_profile_getProfile"
    }
    fn method() -> &'static str {
        "profile_getProfile"
    }
    fn agent() -> &'static str {
        "user"
    }
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfileGetProfileReturnsBanParams {
    #[serde(rename = "bannedUntil")]
    pub banned_until: String,
    #[serde(rename = "id")]
    pub id: f64,
    #[serde(rename = "whoBanned")]
    pub who_banned: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "createdAt")]
    pub created_at: String,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfileGetProfileReturns {
    #[serde(rename = "notice")]
    pub notice: String,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "lastActivity")]
    pub last_activity: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "hasPassword")]
    pub has_password: bool,
    #[serde(rename = "isSubscribedToMailing")]
    pub is_subscribed_to_mailing: bool,
    #[serde(rename = "ban")]
    pub ban: UserProfileGetProfileReturnsBanParams,
    #[serde(rename = "isDeleted")]
    pub is_deleted: bool,
    #[serde(rename = "suspicious")]
    pub suspicious: bool,
    #[serde(rename = "isConfirmed")]
    pub is_confirmed: bool,
    #[serde(rename = "isNicknameChanged")]
    pub is_nickname_changed: bool,
    #[serde(rename = "nickname")]
    pub nickname: String,
    #[serde(rename = "lifeTimeInterestPercent")]
    pub life_time_interest_percent: String,
    #[serde(rename = "registeredAt")]
    pub registered_at: String,
    #[serde(rename = "id")]
    pub id: f64,
    #[serde(rename = "isBanned")]
    pub is_banned: bool,
    #[serde(rename = "lifeTimeInterest")]
    pub life_time_interest: bool,
    #[serde(rename = "email")]
    pub email: String,
}
impl Schema for UserProfileGetProfileReturns {
    fn schema() -> Value {
        serde_json :: json ! ("{\"type\":\"object\",\"properties\":{\"notice\":{\"type\":\"string\"},\"verified\":{\"type\":\"boolean\"},\"lastActivity\":{\"type\":\"string\"},\"userId\":{\"type\":\"string\"},\"hasPassword\":{\"type\":\"boolean\"},\"isSubscribedToMailing\":{\"type\":\"boolean\"},\"ban\":{\"type\":\"object\",\"properties\":{\"bannedUntil\":{\"type\":\"string\"},\"id\":{\"type\":\"integer\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807,\"additionalAttributes\":{\"numberType\":\"Number\"}},\"whoBanned\":{\"type\":\"string\"},\"updatedAt\":{\"type\":\"string\"},\"reason\":{\"type\":\"string\"},\"createdAt\":{\"type\":\"string\"}},\"required\":[\"id\",\"reason\",\"whoBanned\",\"createdAt\",\"updatedAt\",\"bannedUntil\"]},\"isDeleted\":{\"type\":\"boolean\"},\"suspicious\":{\"type\":\"boolean\"},\"isConfirmed\":{\"type\":\"boolean\"},\"isNicknameChanged\":{\"type\":\"boolean\"},\"nickname\":{\"type\":\"string\"},\"lifeTimeInterestPercent\":{\"type\":\"string\"},\"registeredAt\":{\"type\":\"string\"},\"id\":{\"type\":\"integer\",\"minimum\":-9223372036854775808,\"maximum\":9223372036854775807,\"additionalAttributes\":{\"numberType\":\"Number\"}},\"isBanned\":{\"type\":\"boolean\"},\"lifeTimeInterest\":{\"type\":\"boolean\"},\"email\":{\"type\":\"string\"}},\"required\":[\"id\",\"userId\",\"nickname\",\"email\",\"verified\",\"isNicknameChanged\",\"isSubscribedToMailing\",\"suspicious\",\"isConfirmed\",\"notice\",\"isBanned\",\"isDeleted\",\"hasPassword\",\"ban\",\"registeredAt\",\"lastActivity\",\"lifeTimeInterest\",\"lifeTimeInterestPercent\"]}")
    }
}
impl Agent for UserProfileGetProfileReturns {
    fn topic() -> &'static str {
        "user_profile_getProfile"
    }
    fn method() -> &'static str {
        "profile_getProfile"
    }
    fn agent() -> &'static str {
        "user"
    }
}
