// This file are autogenerated on build, everything you write here will be replaced

#![allow(unknown_lints)]
#![allow(clippy::all)]
use crate::Schema;
use serde::de::Deserializer;
use serde::{Deserialize, Serialize};
use serde_json::Value;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserProfileChangeEmailParams {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "newEmail")]
    pub new_email: String,
}
impl Schema for UserProfileChangeEmailParams {
    fn schema() -> Value {
        todo!()
    }
}
pub type UserProfileChangeEmailReturns = bool;
